version: '2'
services:
  hubot:
    build: .
    env_file:
      - /data/hal.env
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - /data/google-generated-creds.json:/usr/src/app/google-generated-creds.json
    restart: always
  redis:
    image: redis
    volumes:
      - data:/data
    expose:
      - "6379"
    restart: always
